- name: Clone remote Github repository
  ansible.builtin.git:
    clone: true
    dest: "{{ github_repository_path }}"
    repo: "{{ github_remote_repository }}"
- name: Remove Git directory from remote repository
  ansible.builtin.file:
    state: absent
    path: "{{ github_repository_path }}/.git"
- name: Add necessary ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: "enabled"
  loop: "{{ firewalld_ports }}"
- name: Start Docker compose file
  community.docker.docker_compose_v2:
    project_src: "{{ github_repository_path }}"
    state: "present"
- name: Check web application
  ansible.builtin.shell:
    cmd: "{{ web_app_check_command }}"
  register: result
  until: result.rc == 0
  retries: 5
  delay: 3

