- name: Clone remote Github repository
  ansible.builtin.git:
    clone: true
    dest: "{{ github_repository_path }}"
    repo: "{{ github_remote_repository }}"
- name: Remove Git directory from remote repository
  ansible.builtin.file:
    state: absent
    path: "{{ github_repository_path }}/.git"
- name: Add necessary ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: "enabled"
  loop: "{{ firewalld_ports }}"
